### PR TITLE
Ecommerce

### PR DESCRIPTION
**Pull request by Konikakonika**
review it I have done with changes now

### CODE REVIEW

**Comment by PriyaDeveloper630** [comment]
> review it I have done with changes now
1.Kindly create a Readme file and add figma link to it. 
2. Also write a little about the problem statement, your inspiration behind taking up this project and color scheme you used in it.

**Comment by PriyaDeveloper630** [comment]
> review it I have done with changes now

@Konikakonika Consider uniformity in background colour and fonts of your screens .

**Comment by Konikakonika** [comment]
@PriyaDeveloper630  done changes

**Comment by Konikakonika** [comment]
done changes review it only

**Comment by Konikakonika** [comment]
@Nitya-Pasrija

**Review by Nitya-Pasrija — APPROVED** [review]

**Pull request merged**
