### PR TITLE
Job Portal design #6

### PR DESCRIPTION
**Pull request by Riddhi050803**
prototype link: https://www.figma.com/file/26bcyPp5BX4niHknokkEbQ/Job-Portal-Design-(Community)?type=design&node-id=0%3A1&mode=design&t=ZaZybwFEPYdzQPWH-1
pdf: [Presentation1.pdf](https://github.com/SnowScriptWinterOfCode/UI-UX-Case-Studies/files/13800609/Presentation1.pdf)
Uploaded pdf which resolve issue #6
kindly review it @PriyaDeveloper630

### CODE REVIEW

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
@Riddhi050803 
Please create a folder named "Job portal" and add the link to the figma files in the readme, as well as any images or pdf that you wish to add in that very folder :)

**Comment by Riddhi050803** [comment]
@Nitya-Pasrija files updated. Please review it again.

**Comment by Riddhi050803** [comment]
changes have been made. @Nitya-Pasrija @captain-sal

**Review by Nitya-Pasrija — APPROVED** [review]
Looks good :)

**Pull request merged**
